### ISSUE TITLE
Linkit not working anymore in statamic v3

### ISSUE THREAD

**Issue by Oleafeon** [riasvdv/statamic-linkit#26]
Hi i have upgraded my site from statamic v2 to v3 and installed the plugin again but now it does not seem to work anymore

I am able to change the stuf in the blueprints but when i look at the page the button does not work anymore see screenshot below

![image](https://user-images.githubusercontent.com/20043831/90763572-36a00180-e2e7-11ea-83ea-f934c4d9957c.png)

this is what i have in my fieldset

```
-
  handle: buttons
  field:
      type: grid
      mode: stacked
      add_row: 'Een nieuwe knop toevoegen'
      fields:
          -
            handle: button
            field:
              type: link_it
              display: Knop
              types:
                - page
                - asset
                - url
              containers:
                  - main
                text: true
                newWindow: true
      display: Knoppen
```

**Comment by riasvdv** [comment]
```
              containers:
                  - main
                text: true
                newWindow: true
```
The indentation here seems wrong, is this because of pasting it in Github? It should look like this:

```
              containers:
                - main
              text: true
              newWindow: true
```

Could you also check your browser's console for errors?
