### ISSUE TITLE
assets link not working anymore

### ISSUE THREAD

**Issue by Oleafeon** [riasvdv/statamic-linkit#32]
it seems that the url is not working for the assets type anymore

it just returns the current page

this is in my template
`{{ blauwe_knop | linkIt:btn btn-custom btn-custom--tertiary-invert }}`

this is the blueprint
```
-
  handle: blauwe_knop
  field:
    types:
      - asset
      - entry
      - custom
      - email
      - tel
      - url
    newWindow: true
    text: true
    aria: false
    append: false
    collections:
      - blog
      - pages
      - portfolio
    containers:
      - documenten
      - images
      - overig
    display: 'Blauwe knop'
    type: link_it
    icon: external-link
    listable: hidden
```

i get this in my md file
```
blauwe_knop:
  type: asset
  newWindow: true
  asset:
    - 'documenten::docs/Placeholder-PDF.pdf'
  text: 'Download tarieven'
  container: documenten
```

when i look on the site it says that the button is set
![image](https://user-images.githubusercontent.com/20043831/117260122-06859800-ae4f-11eb-9a5e-2c1edf9dcabd.png)

but when i look in the devtools the url is not set
![image](https://user-images.githubusercontent.com/20043831/117260191-1c935880-ae4f-11eb-9b06-c19234221843.png)
